# Generated by Django 2.1.5 on 2019-01-26 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='address',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='events',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events_admin', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='city',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='events',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='date',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='events',
            name='description',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='events',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='events',
            name='time',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='events',
            name='type',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='events',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='name',
            field=models.CharField(default=' ', max_length=255, verbose_name='Name'),
        ),
    ]
