# Generated by Django 2.1.5 on 2019-01-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190126_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='image_url',
            field=models.CharField(default='https://www.inform.kz/fotoarticles/20160424104954.jpg', max_length=255),
        ),
    ]
