# Generated by Django 2.1.5 on 2019-01-26 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupings', '0002_auto_20190126_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouping',
            old_name='small_event_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='grouping',
            old_name='small_event_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='grouping',
            old_name='small_event_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='grouping',
            old_name='small_event_desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='grouping',
            old_name='small_min_people',
            new_name='min_people',
        ),
        migrations.RenameField(
            model_name='grouping',
            old_name='small_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='grouping',
            old_name='small_event_time',
            new_name='time',
        ),
    ]
