# Generated by Django 2.1.5 on 2019-01-30 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupings', '0003_auto_20190126_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(default='43.248949', max_length=50)),
                ('longitude', models.CharField(default='76.899709', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='grouping',
            name='coordinates',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='groupings.Coordinate'),
        ),
    ]
