# Generated by Django 2.1.5 on 2019-02-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupings', '0004_auto_20190130_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouping',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='grouping',
            name='latitude',
            field=models.CharField(default='43.248949', max_length=50),
        ),
        migrations.AddField(
            model_name='grouping',
            name='longitude',
            field=models.CharField(default='76.899709', max_length=50),
        ),
        migrations.DeleteModel(
            name='Coordinate',
        ),
    ]
